version: 0.2
env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-17-amazon-corretto/"
phases:
  install:
    commands:
      - sudo yum update; sudo yum install java-17-amazon-corretto
  build:
    commands:
      - ./gradlew clean build
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - build/libs/*.jar
    - appspec.yml
  discard-paths: yes