version: 0.2
install:
  runtime-versions:
    java: corretto11
  build:
    commands:
      - ./gradlew build --scan
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - build/libs/demo-0.0.1-SNAPSHOT.jar
    - scripts/*.sh
    - appspec.yml
