version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk-17
  build:
    commands:
      - ./gradlew clean build
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - build/libs/*.jar
    - appspec.yml
  discard-paths: yes