version: 0.2
install:
  runtime-versions:
    java: corretto11
  build:
    commands:
      - ./gradlew clean build
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - build/libs/*.jar
    - appspec.yml
  discard-paths: yes